### PR TITLE
.NET Standard 2.0 compatibility

### PR DESCRIPTION
**Pull request by sirkirby**
Added additional target for .NET Standard 2.0.

Other changes
* Some additional suggested refactors from Resharper, which reduced the amount of code a bit.
* Package updates

Functional changes
* None

Breaking changes
* None

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hi Chris, thanks for the PR! Looks like there's a CI failure in there somewhere.

**Comment by sirkirby** [comment]
@nblumhardt looks like an issue with the unit test assembly... I'll take a look

**Comment by sirkirby** [comment]
got it... I added the `netstandard2.0` target to the test project, however vs test runner for visual studio does not support netstandard. So removing that target should allow the test to run for `netcoreapp1.1` and `net452`. For now, I think it's ok to leave it that way until they add support. A close alternative could be adding `net461`, which is standard 2 compatible, but honestly 452 should cover it... or we just move up from 452 to 461. I'll push the target removal first and see if that appeases appveyor :)

**Comment by nblumhardt** [comment]
Great, thanks Chris! 👍

**Pull request merged**
