### PR TITLE
Upgraded solution to support .NET Core 1.1 as well as .NET FX 4.5.2

### PR DESCRIPTION
**Pull request by WolfyUK**

### CODE REVIEW

**Comment by nblumhardt** [comment]
Terrific, thanks very much. I've targeted this to a new _dev_ branch so that we should be able to get pre-release packages onto NuGet to test.

It looks like `appveyor.yml` might be missing; the yml at https://github.com/destructurama/attributed/blob/dev/appveyor.yml should work for this.

**Comment by WolfyUK** [comment]
I've added the `.yml` and updated the build script to match the other projects

**Comment by nblumhardt** [comment]
Great, thanks 👍

**Comment by nblumhardt** [comment]
Out now: https://www.nuget.org/packages/Destructurama.JsonNet/1.1.0-dev-00009

**Pull request merged**
